<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>vi_text_editor</AssemblyName>
    <RootNamespace>ViTextEditor</RootNamespace>
    <Version>0.1.8</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ViTextEditor.Core\ViTextEditor.Core.csproj" />
    <PackageReference Include="Scintilla5.NET" Version="7.0.0" />
  </ItemGroup>
</Project>
